### ISSUE TITLE
Unknown device type detected

### ISSUE THREAD

**Issue by tony-tiger** [shauntarves/wyze-sdk#106] opened 2022-11-20 02:08 UTC
Unknown device, Wyze wall switch not detected.  Basic device information listed below.  I tried making a python program that would allow me to turn ON / OFF outside lights. I appears the SDK code does not have support for wall switches. Thanks for your support.

Unknown device type detected ({'mac': 'LD_SS1_7C78BXXXXXXX', 'first_activation_ts': 1657860703000, 'first_binding_ts': 1657860703000, 'enr': '', 'nickname': 'Outside lights', 'timezone_name': 'Pacific', 'product_model': 'LD_SS1', 'product_model_logo_url': '', 'product_type': 'Common', 'hardware_ver': '0.0.0.0', 'firmware_ver': '0.0.1', 'user_role': 1, 'binding_user_nickname': 'user_name@email_adddress.com', 'conn_state': 1, 'conn_state_ts': 1668828989694, 'push_switch': 1, 'device_params': {'switch_state': 0, 'connection_state': 1}, 'is_in_auto': 0, 'event_master_switch': 1, 'parent_device_mac': '', 'parent_device_enr': '', 'binding_ts': 1657860703000, 'timezone_gmt_offset': -10.0})

**Comment by shauntarves** [comment] 2022-11-20 13:25
@tony-tiger Thanks for the issue. I've actually already built support for the Switch, but have been awaiting another set of eyes on it before merging to `master`. Please check out #104 for details. If you're able to give it a test drive, and let me know if it's working for you, I'll merge it in and create a new release!

**Comment by shauntarves** [comment] 2022-12-02 22:26
Closing as duplicate of #66

**Closed by shauntarves** 2022-12-02 22:26 UTC
